### ISSUE TITLE
Footer issue 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#1]
@codextiny 

I had to recreate the agent247.ai website which is now pro.onehomeowner.xyz. I tried to[ copy the custom code](https://github.com/shannonbaldwin/agent247.ai/issues/2#issue-2564516252) to change colors but it did not work. Can you please look into this?

support@homeowner.ai
M!l3st0nesL@bs

**Comment by codextiny** [comment]
@shannonbaldwin 

done, please check
