### ISSUE TITLE
Drop down menu navigation in header on pro.onehomeowner.xyz

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#2]
@codextiny 

How do I get these two menu headers to NOT link? They are not actual pages, only the sub-nav items are to the right of them.

[https://pro.onehomeowner.xyz/](url)
![image](https://github.com/user-attachments/assets/b4c8182d-251a-4ad6-bc4c-6b606f910744)

**Comment by codextiny** [comment]
@shannonbaldwin 

done, please check
