### ISSUE TITLE
Spacing on drop down menu 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#3]
@codextiny Can you please decrease spacing on the platform and who we serve headers in main menu?
![image](https://github.com/user-attachments/assets/8658ded8-645d-4b17-a78a-ef6c709a3cf3)

**Comment by codextiny** [comment]
@shannonbaldwin 

Reduced the spacing but with custom code because there is no option to set spacing.

Thanks
