### ISSUE TITLE
Mobile issue 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#4]
@codextiny This may be due to the layout but is it possible to center this list on mobile?

[https://pro.onehomeowner.xyz/](url)
![image](https://github.com/user-attachments/assets/263df2e7-8edc-468b-9410-5a78021d8d74)

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed but we did it with custom codes, because there is no option to make it center align.

Thanks.
