### ISSUE TITLE
https://pro.onehomeowner.xyz/homeownership

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#5]
@codextiny

1. Please fix these two sections on this page in mobile. The first section needs to be centered and the second section where headers are on left hand side need padding or margin. 

<img width="455" alt="image" src="https://github.com/user-attachments/assets/ea609277-01b4-4c3c-ab5c-3ace98bdf7a9">

<img width="402" alt="image" src="https://github.com/user-attachments/assets/e735c6e9-6033-452f-b0f1-db8382ac5822">

**Comment by codextiny** [comment]
@shannonbaldwin 

Fixed, please check.

you guys have applied negative margin on images, that why page have spacing from right side, make sure to remove negative margins on mobile devices ... for now we removed.

**Comment by shannonbaldwin** [comment]
@codextiny Can you add padding on these sections to match the other sections for mobile?
<img width="312" alt="image" src="https://github.com/user-attachments/assets/142ed250-cdd7-430a-8a8d-3ff9c6685aa5">

**Comment by codextiny** [comment]
@shannonbaldwin 

Fixed, please check
