### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#6]
@codextiny 
Please remove the link option for "Mortgage Services" as we do not have the page for that right now. 

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/7eb9682e-d315-4b47-a302-ded1f1c29e10">

**Comment by codextiny** [comment]
@shannonbaldwin 

done, please check

**Comment by shannonbaldwin** [comment]
@codextiny The CTA in hero is not centering.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/5a9a92b3-eae4-4fa7-8cc3-9c47d9fa74ec">

**Comment by codextiny** [comment]
@shannonbaldwin 

Please mention the url ??

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed, please check

**Comment by shannonbaldwin** [comment]
@codextiny pro.onehomeowner.xyz but I figured it out. :)
