### ISSUE TITLE
Center issue on inner section 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/https-pro.onehomeowner.xyz#9]
@codextiny I am having trouble centering this inner section with the header and subheader above it. [https://pro.onehomeowner.xyz/associations-mls](url)

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/658b1510-a770-4b83-aae9-4c4e5be595ee">

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/10105b4e-04d5-4a1a-bd4b-e19b9c7689f3)

its center aligned, there is no issue with the layout, you guys have added the br and it looks not aligned because of less text ...
